trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'acrlnldevcentralus001.azurecr.io/camelyaml'
  azureSubscriptionEndpoint: 149f1c85-2fa5-49d7-bfb3-608d40c1ef51
  azureContainerRegistry: acrlnldevcentralus001.azurecr.io
  azureResourceGroup: neu-dallas-tech-night-rg
  kubernetesCluster: aks-dtn-dev-centralus-001
  useClusterAdmin: true

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile
- task: Kubernetes@1
  displayName: kubectl apply using arguments
  inputs:
    connectionType: Azure Resource Manager
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureResourceGroup: $(azureResourceGroup)
    kubernetesCluster: $(kubernetesCluster)
    command: apply
    arguments: -f deployment.yaml
    